name: new_version
description: Check if your user has the most recent version of your Flutter app.
version: 0.3.1
homepage: https://github.com/timtraversy/new_version

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^1.0.0
  http: ^0.13.1
  html: ^0.15.0
  url_launcher: ^6.0.2
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
